// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'harness.dart';

/// Represents a file modification patch generated by an agent.
class FilePatch {
  /// Creates a [FilePatch].
  const FilePatch({required this.filePath, required this.content});

  /// Relative file path within the package.
  final String filePath;

  /// Updated file contents.
  final String content;
}

/// Encapsulates code implementation patches produced by an agent.
class ImplementationFix {
  /// Creates an [ImplementationFix].
  const ImplementationFix({required this.patches, this.summary = ''});

  /// The list of file patches to apply.
  final List<FilePatch> patches;

  /// Brief description of the changes.
  final String summary;
}

/// Interface for AI agents generating test cases and implementation patches.
abstract class HarnessAgent {
  /// Generates a failing unit test asserting the reported issue or missing property.
  Future<FilePatch> generateRedTest(HarnessContext context);

  /// Generates implementation patches addressing the test failure.
  Future<ImplementationFix> generateFix(HarnessContext context);
}

/// Sanitizes source code content generated by an AI agent.
///
/// Strips markdown code fences (e.g. ```dart ... ```), normalizes CRLF line
/// endings to LF, and ensures trailing newline termination.
String sanitizeCodeContent(String rawContent) {
  String content = rawContent.replaceAll('\r\n', '\n').trim();

  // Strip leading markdown code fences (```dart, ```swift, ```)
  if (content.startsWith('```')) {
    final int firstNewline = content.indexOf('\n');
    if (firstNewline != -1) {
      content = content.substring(firstNewline + 1).trimLeft();
    }
  }

  // Strip trailing markdown code fences (```)
  if (content.endsWith('```')) {
    final int lastFence = content.lastIndexOf('```');
    content = content.substring(0, lastFence).trimRight();
  }

  return '${content.trimRight()}\n';
}

/// Injects a new test block cleanly before the final closing brace of a test file.
String injectTestCode(String originalContent, String testCode) {
  final int lastBraceIndex = originalContent.lastIndexOf('}');
  if (lastBraceIndex == -1) {
    return '$originalContent\n\n$testCode\n';
  }
  return '${originalContent.substring(0, lastBraceIndex)}\n$testCode\n}\n';
}

/// Applies a targeted search-and-replace edit to [originalContent].
///
/// Supports exact matching as well as whitespace-tolerant line-by-line matching.
/// Throws a [StateError] if [searchBlock] cannot be found.
String applyTargetedEdit({
  required String originalContent,
  required String searchBlock,
  required String replaceBlock,
  String? filePath,
}) {
  final String normalizedOriginal = originalContent.replaceAll('\r\n', '\n');
  final String normalizedSearch = searchBlock.replaceAll('\r\n', '\n').trim();
  final String normalizedReplace = replaceBlock.replaceAll('\r\n', '\n');

  // 1. Trailing whitespace-trimmed line-by-line match
  final List<String> origLines = normalizedOriginal.split('\n');
  final List<String> searchLines = normalizedSearch
      .split('\n')
      .map((String l) => l.trimRight())
      .toList();
  while (searchLines.isNotEmpty && searchLines.first.isEmpty) {
    searchLines.removeAt(0);
  }
  while (searchLines.isNotEmpty && searchLines.last.isEmpty) {
    searchLines.removeLast();
  }

  if (searchLines.isNotEmpty && searchLines.length <= origLines.length) {
    for (var i = 0; i <= origLines.length - searchLines.length; i++) {
      var matches = true;
      for (var j = 0; j < searchLines.length; j++) {
        if (origLines[i + j].trimRight() != searchLines[j]) {
          matches = false;
          break;
        }
      }
      if (matches) {
        final List<String> before = origLines.sublist(0, i);
        final List<String> after = origLines.sublist(i + searchLines.length);
        final List<String> replacementLines = normalizedReplace.split('\n');
        return <String>[...before, ...replacementLines, ...after].join('\n');
      }
    }
  }

  // 2. Leading and trailing whitespace-trimmed line-by-line match (indentation-agnostic)
  final List<String> searchLinesTrimmed = normalizedSearch
      .split('\n')
      .map((String l) => l.trim())
      .toList();
  while (searchLinesTrimmed.isNotEmpty && searchLinesTrimmed.first.isEmpty) {
    searchLinesTrimmed.removeAt(0);
  }
  while (searchLinesTrimmed.isNotEmpty && searchLinesTrimmed.last.isEmpty) {
    searchLinesTrimmed.removeLast();
  }

  if (searchLinesTrimmed.isNotEmpty && searchLinesTrimmed.length <= origLines.length) {
    for (var i = 0; i <= origLines.length - searchLinesTrimmed.length; i++) {
      var matches = true;
      for (var j = 0; j < searchLinesTrimmed.length; j++) {
        if (origLines[i + j].trim() != searchLinesTrimmed[j]) {
          matches = false;
          break;
        }
      }
      if (matches) {
        final List<String> before = origLines.sublist(0, i);
        final List<String> after = origLines.sublist(i + searchLinesTrimmed.length);
        final List<String> replacementLines = normalizedReplace.split('\n');
        return <String>[...before, ...replacementLines, ...after].join('\n');
      }
    }
  }

  // 3. Direct exact substring match fallback
  if (normalizedOriginal.contains(normalizedSearch)) {
    return normalizedOriginal.replaceFirst(normalizedSearch, normalizedReplace);
  }

  final targetDesc = filePath != null ? "file '$filePath'" : 'file';
  throw StateError(
    'Targeted search_block not found in $targetDesc.\n'
    'SEARCH BLOCK:\n$searchBlock\n'
    'Please ensure search_block matches the existing code in $targetDesc with surrounding context.',
  );
}

/// Normalizes common model aliases to valid Gemini model identifiers.
///
/// For example, Google AI Studio does not have a model named `gemini-2.5-flash`
/// (which results in HTTP 404 NOT_FOUND). Common flash aliases are normalized
/// to `gemini-flash-latest`.
String normalizeModelName(String model) {
  final String clean = model.trim().toLowerCase();
  switch (clean) {
    case 'gemini-3.7-flash':
    case '3.7-flash':
    case '3.7 flash':
    case '3.7flash':
      return 'gemini-3.7-flash';
    case 'gemini-3.6-flash':
    case '3.6-flash':
    case '3.6 flash':
    case '3.6flash':
      return 'gemini-3.6-flash';
    case 'gemini-3.5-flash':
    case '3.5-flash':
    case '3.5 flash':
    case '3.5flash':
      return 'gemini-3.5-flash';
    case 'gemini-2.5-flash':
    case '2.5-flash':
    case '2.5flash':
    case 'gemini-flash':
    case 'flash':
      return 'gemini-flash-latest';
    case 'gemini-2.5-pro':
    case '2.5-pro':
    case '2.5 pro':
    case '2.5pro':
    case 'gemini-pro':
    case 'pro':
      return 'gemini-pro-latest';
    case 'gemini-lite':
    case 'flash-lite':
    case 'lite':
      return 'gemini-flash-lite-latest';
    default:
      return model.trim();
  }
}

/// Resolves the default Gemini model identifier.
///
/// Precedence:
/// 1. Explicit [cliModel] argument if passed.
/// 2. `GEMINI_MODEL` environment variable.
/// 3. `.agents/config.json` (`model` key) in [packageDir] or current directory.
/// 4. First model in `fallover_models` in `.agents/config.json`.
/// 5. Fallback default: `gemini-3.6-flash`.
String resolveDefaultModel({String? cliModel, String? packageDir}) {
  if (cliModel != null && cliModel.trim().isNotEmpty) {
    return normalizeModelName(cliModel);
  }
  final String? envModel = Platform.environment['GEMINI_MODEL'];
  if (envModel != null && envModel.trim().isNotEmpty) {
    return normalizeModelName(envModel);
  }

  final candidateDirs = <String>[
    if (packageDir != null)
      packageDir
    else ...<String>[
      Directory.current.path,
      '${Directory.current.path}/packages/in_app_purchase/in_app_purchase_storekit',
    ],
  ];

  for (final dir in candidateDirs) {
    final configFile = File('$dir/.agents/config.json');
    if (configFile.existsSync()) {
      try {
        final String content = configFile.readAsStringSync();
        final dynamic json = jsonDecode(content);
        if (json is Map) {
          if (json['model'] is String && (json['model'] as String).trim().isNotEmpty) {
            return normalizeModelName(json['model'] as String);
          }
          final dynamic rawList =
              json['fallover_models'] ??
              json['failover_models'] ??
              json['fallback_models'] ??
              json['fallovers'] ??
              json['models'];
          if (rawList is List && rawList.isNotEmpty && rawList.first is String) {
            return normalizeModelName(rawList.first as String);
          }
        }
      } catch (_) {
        // Ignore malformed config and continue search.
      }
    }
  }

  return 'gemini-3.6-flash';
}

/// Resolves the list of fallback/fallover models from config.json or defaults.
///
/// Looks for `fallover_models`, `failover_models`, `fallback_models`, `fallovers`,
/// or `models` array in `.agents/config.json`.
/// Defaults to: `['gemini-3.6-flash', 'gemini-3.7-flash', 'gemini-pro-latest']`.
List<String> resolveFallbackModels({String? packageDir}) {
  final candidateDirs = <String>[
    if (packageDir != null)
      packageDir
    else ...<String>[
      Directory.current.path,
      '${Directory.current.path}/packages/in_app_purchase/in_app_purchase_storekit',
    ],
  ];

  for (final dir in candidateDirs) {
    final configFile = File('$dir/.agents/config.json');
    if (configFile.existsSync()) {
      try {
        final String content = configFile.readAsStringSync();
        final dynamic json = jsonDecode(content);
        if (json is Map) {
          final dynamic rawList =
              json['fallover_models'] ??
              json['failover_models'] ??
              json['fallback_models'] ??
              json['fallovers'] ??
              json['models'];
          if (rawList is List) {
            final List<String> models = rawList
                .whereType<String>()
                .map(normalizeModelName)
                .where((String m) => m.isNotEmpty)
                .toList();
            if (models.isNotEmpty) {
              return models;
            }
          }
        }
      } catch (_) {
        // Ignore malformed config and continue search.
      }
    }
  }

  // Ordered by observed availability, not capability. A CI run on 2026-09-16
  // burned roughly six minutes before producing anything: gemini-3.7-flash
  // returned 503 on all five attempts, gemini-pro-latest then returned 429 on
  // all five, and gemini-3.6-flash succeeded on the first try. The work here is
  // mechanical, so a model that answers beats a stronger one that is throttled.
  // `pro` stays in the list as a last resort but is no longer in the hot path,
  // since it is the most rate-limited of the three.
  return const <String>['gemini-3.6-flash', 'gemini-3.7-flash', 'gemini-pro-latest'];
}

/// Builds the prompt passed to Gemini for generating an implementation fix.
String buildFixPrompt(HarnessContext context, {required String fileContext}) {
  final buffer = StringBuffer();
  buffer.writeln('ISSUE #${context.issueNumber}');
  buffer.writeln('Title: ${context.issueTitle}');
  buffer.writeln('Body: ${context.issueBody}');
  buffer.writeln();

  if (context.redTestCode != null && context.redTestCode!.trim().isNotEmpty) {
    buffer.writeln('REPRODUCTION TEST THAT FAILED:');
    buffer.writeln(context.redTestCode!.trim());
    buffer.writeln();
  }

  buffer.writeln('TEST FAILURE & STACK TRACE:');
  buffer.writeln(context.lastTestFailureSummary ?? 'No failure summary recorded');
  buffer.writeln();

  buffer.writeln('SOURCE FILES:');
  buffer.write(fileContext);

  return buffer.toString();
}

/// Default AI agent using the Gemini API with structured JSON output.
class GeminiHarnessAgent implements HarnessAgent {
  /// Creates a [GeminiHarnessAgent].
  GeminiHarnessAgent({
    this.apiKey,
    this.gcpAccessToken,
    String? model,
    List<String>? fallbackModels,
    String? packageDir,
    this.retryDelay = const Duration(seconds: 5),
    this.maxNetworkRetries = 5,
  }) : model = resolveDefaultModel(cliModel: model, packageDir: packageDir),
       fallbackModels = fallbackModels ?? resolveFallbackModels(packageDir: packageDir);

  /// Optional explicit Gemini API key.
  final String? apiKey;

  /// Optional explicit GCP access token.
  final String? gcpAccessToken;

  /// Gemini model identifier.
  final String model;

  /// Fallback/fallover models to try in sequence upon failure or rate limit.
  final List<String> fallbackModels;

  /// Delay between network retries when receiving transient errors (e.g. HTTP 503/429).
  final Duration retryDelay;

  /// Maximum network attempts for transient HTTP errors before throwing.
  final int maxNetworkRetries;

  static const Map<String, dynamic> _redTestSchema = <String, dynamic>{
    'type': 'OBJECT',
    'properties': <String, dynamic>{
      'file_path': <String, dynamic>{
        'type': 'STRING',
        'description': 'The relative path to the test file.',
      },
      'test_code': <String, dynamic>{
        'type': 'STRING',
        'description':
            'The new reproduction test function (e.g. test("...", () async { ... });) that asserts the missing property or bug and fails on clean code. Must be raw source code only without markdown code blocks.',
      },
      'test_name': <String, dynamic>{
        'type': 'STRING',
        'description': 'Name of the added reproduction test.',
      },
    },
    'required': <String>['file_path', 'test_code'],
  };

  static const Map<String, dynamic> _fixSchema = <String, dynamic>{
    'type': 'OBJECT',
    'properties': <String, dynamic>{
      'summary': <String, dynamic>{
        'type': 'STRING',
        'description': 'Brief summary of the changes made.',
      },
      'edits': <String, dynamic>{
        'type': 'ARRAY',
        'description':
            'Targeted search-and-replace edits for existing files. Preferred for adding or modifying fields/methods.',
        'items': <String, dynamic>{
          'type': 'OBJECT',
          'properties': <String, dynamic>{
            'file_path': <String, dynamic>{
              'type': 'STRING',
              'description': 'Relative path of the existing file to edit.',
            },
            'search_block': <String, dynamic>{
              'type': 'STRING',
              'description':
                  'Exact unique existing code snippet to find (include 2-3 lines of surrounding context).',
            },
            'replace_block': <String, dynamic>{
              'type': 'STRING',
              'description': 'Replacement code snippet to substitute in place of search_block.',
            },
          },
          'required': <String>['file_path', 'search_block', 'replace_block'],
        },
      },
      'new_files': <String, dynamic>{
        'type': 'ARRAY',
        'description': 'Complete file content for brand new files only.',
        'items': <String, dynamic>{
          'type': 'OBJECT',
          'properties': <String, dynamic>{
            'file_path': <String, dynamic>{
              'type': 'STRING',
              'description': 'Relative path of the new file.',
            },
            'content': <String, dynamic>{
              'type': 'STRING',
              'description': 'Complete raw file content.',
            },
          },
          'required': <String>['file_path', 'content'],
        },
      },
      'patches': <String, dynamic>{
        'type': 'ARRAY',
        'description': 'Optional legacy full-file patches fallback.',
        'items': <String, dynamic>{
          'type': 'OBJECT',
          'properties': <String, dynamic>{
            'file_path': <String, dynamic>{
              'type': 'STRING',
              'description': 'Relative path of the modified file.',
            },
            'updated_content': <String, dynamic>{
              'type': 'STRING',
              'description': 'Complete updated content for the file.',
            },
          },
          'required': <String>['file_path', 'updated_content'],
        },
      },
    },
    'required': <String>['summary'],
  };

  int _callCount = 0;

  Future<Map<String, dynamic>> _callGemini({
    required String prompt,
    required String systemInstruction,
    required Map<String, dynamic> responseSchema,
    HarnessContext? context,
    String? actionName,
  }) async {
    _callCount++;
    final prefix = '${_callCount.toString().padLeft(2, "0")}_${actionName ?? "call"}';
    if (context != null) {
      context.recordArtifact(
        '${prefix}_prompt.txt',
        'SYSTEM INSTRUCTION:\n$systemInstruction\n\nPROMPT:\n$prompt',
      );
    }

    final String? effectiveApiKey = apiKey ?? Platform.environment['GEMINI_API_KEY'];
    final String? effectiveToken = gcpAccessToken ?? Platform.environment['GCP_ACCESS_TOKEN'];

    final candidateModels = <String>[];
    for (final candidate in <String>[model, ...fallbackModels]) {
      if (!candidateModels.contains(candidate)) {
        candidateModels.add(candidate);
      }
    }

    final requestBody = <String, dynamic>{
      'contents': <Map<String, dynamic>>[
        <String, dynamic>{
          'role': 'user',
          'parts': <Map<String, dynamic>>[
            <String, dynamic>{'text': prompt},
          ],
        },
      ],
      'systemInstruction': <String, dynamic>{
        'parts': <Map<String, dynamic>>[
          <String, dynamic>{'text': systemInstruction},
        ],
      },
      'generationConfig': <String, dynamic>{
        'temperature': 0.1,
        'responseMimeType': 'application/json',
        'responseSchema': responseSchema,
      },
    };

    final httpClient = HttpClient();
    try {
      for (var modelIdx = 0; modelIdx < candidateModels.length; modelIdx++) {
        final String activeModel = candidateModels[modelIdx];
        final Uri requestUri;
        final headers = <String, String>{'Content-Type': 'application/json'};

        if (effectiveToken != null && effectiveToken.isNotEmpty) {
          requestUri = Uri.parse(
            'https://us-central1-aiplatform.googleapis.com/v1/projects/flutter-dev/locations/us-central1/publishers/google/models/$activeModel:generateContent',
          );
          headers['Authorization'] = 'Bearer $effectiveToken';
        } else if (effectiveApiKey != null && effectiveApiKey.isNotEmpty) {
          // Sent as a header, not a `?key=` query parameter: a Uri holding the
          // key leaks it through `HttpException.toString()` into run logs and
          // CI output. See the matching comment in triage.dart.
          requestUri = Uri.parse(
            'https://generativelanguage.googleapis.com/v1beta/models/$activeModel:generateContent',
          );
          headers['x-goog-api-key'] = effectiveApiKey;
        } else {
          throw StateError(
            'No credentials found for HarnessAgent. Set GEMINI_API_KEY or GCP_ACCESS_TOKEN.',
          );
        }

        for (var networkAttempt = 1; networkAttempt <= maxNetworkRetries; networkAttempt++) {
          final HttpClientRequest request = await httpClient.postUrl(requestUri);
          headers.forEach((String key, String value) {
            request.headers.set(key, value);
          });
          // See the matching comment in triage.dart: `write(String)` encodes as
          // latin-1. This prompt embeds both the issue text and package source,
          // so a single non-Latin-1 character anywhere in either would throw
          // before the request was sent.
          request.add(utf8.encode(jsonEncode(requestBody)));

          final HttpClientResponse response = await request.close();
          final String responseText = await response.transform(utf8.decoder).join();
          if (context != null) {
            context.recordArtifact('${prefix}_response.json', responseText);
          }

          if (response.statusCode == 503 || response.statusCode == 429) {
            if (networkAttempt < maxNetworkRetries) {
              final String? retryAfterHeader = response.headers.value('retry-after');
              final int? parsedRetryAfter = retryAfterHeader != null
                  ? int.tryParse(retryAfterHeader.trim())
                  : null;
              final int exponentialSeconds = retryDelay == Duration.zero
                  ? 0
                  : math.min(60, (retryDelay.inSeconds * math.pow(2, networkAttempt - 1)).toInt());
              final int delaySeconds = parsedRetryAfter ?? exponentialSeconds;
              final delay = Duration(seconds: delaySeconds);

              context?.log(
                '⚠️ Gemini model ($activeModel) busy/unavailable (${response.statusCode}). '
                'Pausing ${delay.inSeconds}s before retry '
                '(attempt $networkAttempt of $maxNetworkRetries)...',
              );
              if (delay > Duration.zero) {
                await Future<void>.delayed(delay);
              }
              continue;
            } else if (modelIdx + 1 < candidateModels.length) {
              final String nextModel = candidateModels[modelIdx + 1];
              context?.log(
                '⚠️ Gemini model ($activeModel) unavailable (${response.statusCode}) after $maxNetworkRetries attempts. '
                'Failing over to healthy candidate model ($nextModel)...',
              );
              break;
            }
          }

          if (response.statusCode == 404 && modelIdx + 1 < candidateModels.length) {
            final String nextModel = candidateModels[modelIdx + 1];
            context?.log(
              '⚠️ Gemini model ($activeModel) not found (404). '
              'Failing over to healthy candidate model ($nextModel)...',
            );
            break;
          }

          if (response.statusCode != 200) {
            throw HttpException(
              'Gemini API request failed (${response.statusCode}): $responseText',
              uri: requestUri,
            );
          }

          final jsonResponse = jsonDecode(responseText) as Map<String, dynamic>;
          final candidates = jsonResponse['candidates'] as List<dynamic>?;
          if (candidates == null || candidates.isEmpty) {
            throw StateError('No candidates returned from Gemini API.');
          }

          final candidate = candidates.first as Map<String, dynamic>;
          final content = candidate['content'] as Map<String, dynamic>?;
          final parts = content?['parts'] as List<dynamic>?;
          final firstPart = parts?.first as Map<String, dynamic>?;
          final text = firstPart?['text'] as String?;
          if (text == null || text.isEmpty) {
            throw StateError('Candidate part contained no text.');
          }

          return jsonDecode(text) as Map<String, dynamic>;
        }
      }

      throw StateError('Gemini API call failed after network attempts across candidate models.');
    } finally {
      // See triage.dart: a plain `close()` waits on a socket that a failed
      // body write left half-open. Here it would stall once per attempt, so
      // the harness could burn its whole job timeout doing nothing.
      httpClient.close(force: true);
    }
  }

  @override
  Future<FilePatch> generateRedTest(HarnessContext context) async {
    final String relativeTestFile =
        context.testFilePath ??
        (context.packageName == 'in_app_purchase_storekit'
            ? 'test/in_app_purchase_storekit_2_platform_test.dart'
            : 'test/${context.packageName}_test.dart');

    final String packageDir = context.resolvePackagePath();
    final testFile = File('$packageDir/$relativeTestFile');
    final String existingContent = testFile.existsSync() ? testFile.readAsStringSync() : '';

    final systemInstruction =
        '''
You are an expert Flutter engineer contributing to flutter/packages for ${context.packageName}.
Your objective is to write a single reproduction unit test (TDD FAIL_TO_PASS).
The test MUST assert the missing property, method, or reported bug on clean code.
Because the feature is not implemented yet, this test MUST fail on clean code (e.g. referencing a getter that is not yet defined, or expecting a non-null value).

GUIDELINES:
- STOREKIT 2 CONTRACT: StoreKit 2 is strictly Pigeon-typed. StoreKit 2 classes (SK2Transaction, SK2Product, etc.) DO NOT HAVE `fromMap`, `toMap`, or `fromJson` factory methods! NEVER call `.fromMap()` or `.toMap()`.
- To test StoreKit 2, prefer calling the platform API methods (such as `await SK2Transaction.unfinishedTransactions()` or `await SK2Transaction.transactions()`) or instantiating the class directly with its named constructor (`SK2Transaction(...)`).
- Note that `fakeStoreKit2Platform` (in `test/fakes/fake_storekit_platform.dart`) provides mock responses for platform methods like `unfinishedTransactions()`.
- Follow repo conventions and avoid redundant local type annotations (e.g. use `final x = ...`, not `final Type x = ...`).
- Do NOT modify production files.
- Provide your new test block in `test_code`. Return RAW code only without markdown code fences.
''';

    final String contextSnippet;
    final List<String> lines = existingContent.split('\n');
    if (lines.length > 80) {
      contextSnippet =
          '// ... (earlier tests omitted for brevity) ...\n${lines.sublist(lines.length - 80).join('\n')}';
    } else {
      contextSnippet = existingContent;
    }

    final prompt =
        '''
ISSUE #${context.issueNumber}
Title: ${context.issueTitle}
Body: ${context.issueBody}

PREVIOUS TEST INVARIANT FAILURE (if any):
${context.lastTestFailureSummary ?? 'None'}

TARGET TEST FILE: $relativeTestFile
EXISTING TESTS (tail snippet):
$contextSnippet
''';

    final Map<String, dynamic> response = await _callGemini(
      prompt: prompt,
      systemInstruction: systemInstruction,
      responseSchema: _redTestSchema,
      context: context,
      actionName: 'red_test',
    );

    final testCode = response['test_code'] as String?;
    if (testCode == null || testCode.trim().isEmpty) {
      throw StateError('Agent did not provide required test_code in response.');
    }

    final String sanitizedCode = sanitizeCodeContent(testCode);
    final String updatedContent = injectTestCode(existingContent, sanitizedCode);

    context.redTestCode = sanitizedCode;
    testFile.writeAsStringSync(updatedContent);

    return FilePatch(filePath: relativeTestFile, content: updatedContent);
  }

  @override
  Future<ImplementationFix> generateFix(HarnessContext context) async {
    final String packageDir = context.resolvePackagePath();

    final candidateFiles = <String>[
      'pigeons/sk2_pigeon.dart',
      'darwin/in_app_purchase_storekit/Sources/in_app_purchase_storekit/StoreKit2/StoreKit2Translators.swift',
      'lib/src/store_kit_2_wrappers/sk2_transaction_wrapper.dart',
      'test/fakes/fake_storekit_platform.dart',
    ];

    final fileContextBuffer = StringBuffer();
    for (final relPath in candidateFiles) {
      final file = File('$packageDir/$relPath');
      if (file.existsSync()) {
        fileContextBuffer.writeln('=== FILE: $relPath ===');
        fileContextBuffer.writeln(file.readAsStringSync());
        fileContextBuffer.writeln();
      }
    }

    final systemInstruction =
        '''
You are an expert Flutter engineer contributing to flutter/packages for ${context.packageName}.
You are implementing the fix for Issue #${context.issueNumber}.
A reproduction test has been written and failed as expected.

DIAGNOSIS GUIDELINES:
- Analyze the REPRODUCTION TEST THAT FAILED and the TEST FAILURE & STACK TRACE to pinpoint exactly what the test expected, what value was returned (or what error occurred), and at what line.
- Use this to determine if the issue is a missing native translator property, missing wrapper converter mapping, or missing mock setup.

STRICT INVARIANTS:
1. NEVER modify pubspec.yaml or CHANGELOG.md. PRs with these edits are rejected immediately.
2. DO NOT manually edit generated files (*.g.dart, *.g.swift). Pigeon code generator runs automatically after your edits.
3. PREFER MINIMAL TARGETED EDITS in `edits`: Provide `search_block` and `replace_block` for modifications.
   - `search_block` MUST be minimal and exact: 1 to 2 lines is ideal (e.g. just the single line right before your insertion). Do NOT include large blocks of surrounding context lines.
   - `replace_block` MUST be the replacement snippet substituted in place of `search_block`.
   - Do NOT rewrite entire files when only adding or modifying a few lines or fields.
4. PIGEON CONTRACT & TEST FAKES (when exposing new properties or methods):
   Step 1 (Pigeon IDL): In `pigeons/*.dart`, add the field to the message class (and to the constructor parameter list if a constructor exists).
   Step 2 (Native Platform Translator): In native files (e.g. `StoreKit2Translators.swift`), map the native property into the Pigeon message.
   Step 3 (Dart Wrapper Class): In wrapper classes (e.g. `sk2_transaction_wrapper.dart`):
     a) Add the `final` field declaration with doc comments (///).
     b) Add the parameter to the class constructor parameter list (`this.<field>,` or `required this.<field>,`).
     c) Map the field in the converter method (e.g. `convertFromPigeon()`).
     d) NEVER create `fromMap` or `toMap` methods and do NOT call nonexistent `SKError.fromMap()`. StoreKit 2 is 100% typed via Pigeon messages and instantiates wrappers in `convertFromPigeon()`.
   Step 4 (Test Fakes & Mocks): In test fake files (e.g. `test/fakes/fake_storekit_platform.dart`), if fake transaction instances (such as `unfinishedTransactionsList` or `createRestoredTransaction`) are queried by unit tests, populate the new property with a valid mock value so assertions like `isNotNull` pass cleanly.
5. Ensure all public Dart members have complete doc comments (///).
6. Return RAW code only in `replace_block`. Do NOT wrap in markdown code fences (no ```dart or ```).
''';

    final String prompt = buildFixPrompt(context, fileContext: fileContextBuffer.toString());

    final Map<String, dynamic> response = await _callGemini(
      prompt: prompt,
      systemInstruction: systemInstruction,
      responseSchema: _fixSchema,
      context: context,
      actionName: 'implementation_fix',
    );

    final String summary = response['summary'] as String? ?? 'Fix applied';
    final List<dynamic> rawEdits = response['edits'] as List<dynamic>? ?? <dynamic>[];
    final List<dynamic> rawNewFiles = response['new_files'] as List<dynamic>? ?? <dynamic>[];
    final List<dynamic> rawPatches = response['patches'] as List<dynamic>? ?? <dynamic>[];
    final patches = <FilePatch>[];

    // 1. Process targeted edits (preferred)
    for (final raw in rawEdits) {
      final editMap = raw as Map<String, dynamic>;
      final path = editMap['file_path'] as String;
      final searchBlock = editMap['search_block'] as String;
      final replaceBlock = editMap['replace_block'] as String;

      final file = File('$packageDir/$path');
      if (!file.existsSync()) {
        throw StateError('File not found for targeted edit: $path');
      }
      final String currentContent = file.readAsStringSync();
      final String updatedContent = applyTargetedEdit(
        originalContent: currentContent,
        searchBlock: searchBlock,
        replaceBlock: replaceBlock,
        filePath: path,
      );
      file.writeAsStringSync(updatedContent);
      patches.add(FilePatch(filePath: path, content: updatedContent));
    }

    // 2. Process new files
    for (final raw in rawNewFiles) {
      final fileMap = raw as Map<String, dynamic>;
      final path = fileMap['file_path'] as String;
      final String content = sanitizeCodeContent(fileMap['content'] as String);

      final file = File('$packageDir/$path');
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(content);
      patches.add(FilePatch(filePath: path, content: content));
    }

    // 3. Process legacy full-file patches if provided
    for (final raw in rawPatches) {
      final patchMap = raw as Map<String, dynamic>;
      final path = patchMap['file_path'] as String;
      final String content = sanitizeCodeContent(patchMap['updated_content'] as String);

      final file = File('$packageDir/$path');
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(content);
      patches.add(FilePatch(filePath: path, content: content));
    }

    return ImplementationFix(patches: patches, summary: summary);
  }
}
