// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:io';

/// Represents the outcome of executing a package test.
class TestRunResult {
  /// Creates a [TestRunResult].
  const TestRunResult({required this.exitCode, required this.stdout, required this.stderr});

  /// The exit code of the test process (0 for success, non-zero for failure).
  final int exitCode;

  /// Standard output generated by the test runner.
  final String stdout;

  /// Standard error generated by the test runner.
  final String stderr;

  /// Whether the test run succeeded (exit code 0).
  bool get passed => exitCode == 0;

  /// Formatted summary of the failure output for logging and context tracking.
  String get failureSummary {
    if (passed) {
      return 'Test passed (exit code 0)';
    }
    final String combined = '$stderr\n$stdout'.trim();
    if (combined.isEmpty) {
      return 'Test exited with code $exitCode without output.';
    }
    final List<String> lines = combined.split('\n');
    if (lines.length > 50) {
      return '${lines.take(50).join('\n')}\n... [truncated]';
    }
    return combined;
  }
}

/// Interface for executing package test suites.
abstract class TestRunner {
  /// Runs the test at [testFilePath] inside [workingDirectory].
  Future<TestRunResult> runTest({required String testFilePath, required String workingDirectory});

  /// Runs all package unit tests inside [workingDirectory] to verify zero regressions.
  Future<TestRunResult> runSuite({required String workingDirectory});
}

/// Default test runner that invokes `flutter test`.
class FlutterTestRunner implements TestRunner {
  /// Creates a [FlutterTestRunner].
  const FlutterTestRunner();

  @override
  Future<TestRunResult> runTest({
    required String testFilePath,
    required String workingDirectory,
  }) async {
    final ProcessResult result = await Process.run('flutter', <String>[
      'test',
      testFilePath,
    ], workingDirectory: workingDirectory);
    return TestRunResult(
      exitCode: result.exitCode,
      stdout: result.stdout as String? ?? '',
      stderr: result.stderr as String? ?? '',
    );
  }

  @override
  Future<TestRunResult> runSuite({required String workingDirectory}) async {
    final ProcessResult result = await Process.run('flutter', <String>[
      'test',
    ], workingDirectory: workingDirectory);
    return TestRunResult(
      exitCode: result.exitCode,
      stdout: result.stdout as String? ?? '',
      stderr: result.stderr as String? ?? '',
    );
  }
}
